In [2]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

np.linalg.inv(array1)

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [3]:
array2 = np.linalg.inv(array1)
np.matmul(array1,array2)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.38777878e-17,  1.00000000e+00]])

In [8]:
#2. 運用上列array計算特徵值、特徵向量?
array1a, array1b = np.linalg.eig(array1)
#特徵值
array1a 

array([13.,  2.])

In [9]:
#特徵向量 
array1b

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [1]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

NameError: name 'np' is not defined